# dp_connect with s3 board with bad creds

    Code
      dp_connect(board_params = board_params, creds = creds)
    Message <cliMessage>
      x Encountered error in dp_connect.
      ! Make sure crendentials passed are correct.
      ! Networking constraints (e.g. vpn) may be blocking communication.
      x SerializationError (HTTP 403). failed to read from query HTTP response body403

